language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
matrix:
  fast_finish: true
install:
  - npm i
script:
  - npm run lint
  - npm test
after_script:
  - npm install -g codecov
  - npm run codecov
